/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vovas_lazyv_server_NativeEasyKeySender */

#ifndef _Included_com_vovas_lazyv_server_NativeEasyKeySender
#define _Included_com_vovas_lazyv_server_NativeEasyKeySender
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_vovas_lazyv_server_NativeEasyKeySender
 * Method:    sendEasyKey
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_vovas_lazyv_server_NativeEasyKeySender_sendEasyKey
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_vovas_lazyv_server_NativeEasyKeySender
 * Method:    sendChar
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_com_vovas_lazyv_server_NativeEasyKeySender_sendChar
  (JNIEnv *, jobject, jchar);

#ifdef __cplusplus
}
#endif
#endif
